// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_cognito_identity_pool_id: "us-west-2:d9f67098-98bd-426c-9968-50d224823c59",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_qoJRSynq8",
  aws_user_pools_web_client_id: "4cbbgt3ua4bo0lb6npcrj6oi0n",
  aws_cloud_logic_custom: [
    {
      name: "stripe",
      endpoint: "https://4013p6z3pd.execute-api.us-west-2.amazonaws.com/Prod",
      region: "us-west-2",
    },
  ],
  aws_appsync_graphqlEndpoint: "https://git5ageybze33ly2vl272xhtba.appsync-api.us-west-2.amazonaws.com/graphql",
  aws_appsync_region: "us-west-2",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_content_delivery_bucket: "harrisonlakeshuttles-20190301220810-hostingbucket",
  aws_content_delivery_bucket_region: "us-west-2",
  aws_content_delivery_url: "https://dksc1v1uij8bd.cloudfront.net",
};

export default awsmobile;
