// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:e24bdfaf-f1b0-4bf3-82ad-fb33e206f550",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_9q7lRTMoj",
    "aws_user_pools_web_client_id": "5amiaekmarltpcaha881t9s53n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mvvoculilzbw7ciwz7xuoneu7q.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "apihlsreststripe1",
            "endpoint": "https://czs3kvf7fj.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_content_delivery_bucket": "hls-fixed-hosting-dev-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d1qutao1oji97r.cloudfront.net"
};


export default awsmobile;
